### PR TITLE
Don't skip processing flipped imgs.

### PR DESCRIPTION
**Pull request by Zehaos**
Don't skip processing flipped imgs.

### CODE REVIEW

**Comment by tkuanlun350** [comment]
It seems that you combined roi_db with mask_db, but the original code is correct right ? Does this commit simply refactor the code base or it's a bug fixing ?

**Comment by Zehaos** [comment]
The ori code has a small performance gap with our pretrained model.( ~ 1% drop on AP100, no effect on AP50). With this commit, the code now should reproduce our result on cityscapes dataset.

**Comment by DevinCheung** [comment]
@Zehaos What is flipped used for?

**Comment by huangzehao** [comment]
@DevinCheung Data augmentation.

**Pull request merged**
